title: CJ Jessett
description: >
  CJ Jessett. I'm a web developer, rock climber, and skiing enthusiast.

url: "localhost:4000"

email: me@cjjessett.com
twitter: //twitter.com/kep20f
github:  //github.com/cjessett
linkedin: //linkedin.com/in/cjessett
instagram: //instagram.com/cjessett


# Build settings
markdown: kramdown

